version: '3.9'

services:
  gpt-sql-scripts:
    build: .
    environment:
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      # Pinecone (vector DB)
      PINECONE_API_KEY: ${PINECONE_API_KEY:-}
      PINECONE_ENV: ${PINECONE_ENV:-}
    ports:
      - '8000:8000'
    entrypoint: uvicorn
    command:
      - "app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
