# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.{default}/":
    type: upstream
    upstream: "app:get-sample-call-logs"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"